[project]
name = "program"
version = "0.1.0"
description = "Add your descriptions here"
dependencies = [
  "numpy",
  "pandas",
]
authors = [
  {name = "Example Person", email = "someone@example.com"},
]
readme = "README.md"
license-files = ["LICEN[CS]E*", "vendored/licenses/*.txt", "AUTHORS.md"]
classifiers = [
  "Private :: Do Not Upload"
]
